### ISSUE TITLE
Using a custom Plumed installation

### ISSUE THREAD

**Issue by ccalia** [openmm/openmm-plumed#87]
Hello,

I have a conda installation of OpenMM and I had no problems using Plumed via conda install -c conda-forge openmm-plumed. But I need to use other Plumed modules so I want to use my existing Plumed version instead of what comes with openmm-plumed from conda. I have tried to accomplish this in two different ways, neither of which has worked.

First I tried based on #66:

My LD_LIBRARY_PATH includes /data/software/repo/plumed/2.8.0/lib and I tried conda remove --force plumed, but then I can't import PlumedForce:

```
>>> from openmmplumed import PlumedForce
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ccalia/anaconda3/envs/openmm_env_plumed2.8.0/lib/python3.12/site-packages/openmmplumed.py", line 12, in <module>
    import _openmmplumed
ImportError: /home/ccalia/anaconda3/envs/openmm_env_plumed2.8.0/lib/python3.12/site-packages/../../libOpenMMPlumed.so: undefined symbol: plumed_free
```

So I instead tried to build the openmm-plumed plugin from source specifying the Plumed that I want to use, starting with a new conda env: 

conda create --name openmm_env2
conda activate openmm_env2
conda install -c conda-forge openmm cudatoolkit=11.3

git clone https://github.com/openmm/openmm-plumed.git
cd openmm-plumed/
mkdir build
cd build/
cmake .. -DOPENMM_DIR=$CONDA_PREFIX -DPLUMED_INCLUDE_DIR=/data/software/repo/plumed/2.8.0/include/plumed -DPLUMED_LIBRARY_DIR=/data/software/repo/plumed/2.8.0/lib -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make install

But make install gives an error:

```
Scanning dependencies of target OpenMMPlumed
[ 11%] Building CXX object CMakeFiles/OpenMMPlumed.dir/openmmapi/src/PlumedForce.cpp.o
[ 22%] Building CXX object CMakeFiles/OpenMMPlumed.dir/openmmapi/src/PlumedForceImpl.cpp.o
[ 33%] Building CXX object CMakeFiles/OpenMMPlumed.dir/serialization/src/PlumedForceProxy.cpp.o
[ 44%] Building CXX object CMakeFiles/OpenMMPlumed.dir/serialization/src/PlumedSerializationProxyRegistration.cpp.o
[ 55%] Linking CXX shared library libOpenMMPlumed.so
[ 55%] Built target OpenMMPlumed
Scanning dependencies of target TestPlumedForce
[ 66%] Building CXX object tests/CMakeFiles/TestPlumedForce.dir/TestPlumedForce.cpp.o
[ 77%] Linking CXX executable TestPlumedForce
CMakeFiles/TestPlumedForce.dir/TestPlumedForce.cpp.o: In function `testForce(OpenMM::Platform&)':
TestPlumedForce.cpp:(.text+0x4b9): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestPlumedForce.cpp:(.text+0x953): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestPlumedForce.cpp:(.text+0xbfb): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestPlumedForce.cpp:(.text+0xfd3): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestPlumedForce.cpp:(.text+0x1290): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestPlumedForce.dir/TestPlumedForce.cpp.o: In function `testMetadynamics(OpenMM::Platform&)':
TestPlumedForce.cpp:(.text+0x155a): undefined reference to `OpenMM::CustomExternalForce::CustomExternalForce(std::string const&)'
TestPlumedForce.cpp:(.text+0x1901): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestPlumedForce.dir/TestPlumedForce.cpp.o: In function `testWellTemperedMetadynamics(OpenMM::Platform&)':
TestPlumedForce.cpp:(.text+0x1be3): undefined reference to `OpenMM::CustomExternalForce::CustomExternalForce(std::string const&)'
TestPlumedForce.cpp:(.text+0x2073): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestPlumedForce.dir/TestPlumedForce.cpp.o: In function `testMassesCharges(OpenMM::Platform&)':
TestPlumedForce.cpp:(.text+0x2618): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestPlumedForce.cpp:(.text+0x2711): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestPlumedForce.cpp:(.text+0x292c): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
TestPlumedForce.cpp:(.text+0x2a25): undefined reference to `OpenMM::throwException(char const*, int, std::string const&)'
CMakeFiles/TestPlumedForce.dir/TestPlumedForce.cpp.o:TestPlumedForce.cpp:(.text+0x2bee): more undefined references to `OpenMM::throwException(char const*, int, std::string const&)' follow
CMakeFiles/TestPlumedForce.dir/TestPlumedForce.cpp.o: In function `main':
TestPlumedForce.cpp:(.text+0x3183): undefined reference to `OpenMM::Platform::getDefaultPluginsDirectory()'
TestPlumedForce.cpp:(.text+0x3195): undefined reference to `OpenMM::Platform::loadPluginsFromDirectory(std::string const&)'
../libOpenMMPlumed.so: undefined reference to `OpenMM::CustomCPPForceImpl::getKernelNames()'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::setStringProperty(std::string const&, std::string const&)'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::setBoolProperty(std::string const&, bool)'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationProxy::SerializationProxy(std::string const&)'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::getStringProperty(std::string const&) const'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::getBoolProperty(std::string const&) const'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::createChildNode(std::string const&)'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::getDoubleProperty(std::string const&) const'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::setDoubleProperty(std::string const&, double)'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::setIntProperty(std::string const&, int)'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::getChildNode(std::string const&) const'
../libOpenMMPlumed.so: undefined reference to `OpenMM::SerializationNode::getIntProperty(std::string const&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/TestPlumedForce] Error 1
make[1]: *** [tests/CMakeFiles/TestPlumedForce.dir/all] Error 2
make: *** [all] Error 2
```

So I tried editing CMakeCache.txt as suggested by ljmartin in #16:

Changed:
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=

To:
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-D_GLIBCXX_USE_CXX11_ABI=0

And still got the error.

I would be very grateful for help addressing the problems with either of the strategies I've tried to make OpenMM use my Plumed. Specific details about what to do would be especially appreciated, as I am not very experienced in installing softwares.

Thanks so much!

**Comment by peastman** [comment]
That looks like the OpenMM-Plumed plugin is built with a different version on the ABI than OpenMM.  Notice that the errors all involve calls to OpenMM functions, and they all involve strings, which are represented differently in the two ABIs.

Everything you're going to link together needs to use the same ABI.  If you compile Plumed and OpenMM-Plumed with the old ABI, you also need to compile OpenMM with it.  Or alternatively you could try to compile Plumed with the new ABI.

**Comment by ccalia** [comment]
Thank you so much for the input!

I tried reinstalling Plumed, and building openmm-plumed with -D_GLIBCXX_USE_CXX11_ABI=0 or -D_GLIBCXX_USE_CXX11_ABI=1, still never got past the errors when I do make install.

But after reinstalling Plumed 2.9.1 from scratch, the original strategy worked. So the process that got me to what I wanted was:

conda install -c conda-forge openmm cudatoolkit=11.3
conda install -c conda-forge openmm-plumed
conda remove --force plumed

export LD_LIBRARY_PATH=/home/ccalia/Codes/Plumed/plumed-2.9.1/myprefix/lib:$LD_LIBRARY_PATH

Plus installing Plumed 2.9.1 from scratch.

Thanks again!
